name: Create Release

on:
  push:
    branches: main
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Get the latest tag
        id: get_latest_tag
        run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)

      - name: Create new tag
        id: create_new_tag
        run: |
          latest_tag=$(echo ${{ steps.get_latest_tag.outputs.tag }} | sed 's/v//')
          new_tag=v$((latest_tag + 1))
          echo ::set-output name=new_tag::$new_tag

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_new_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_new_tag.outputs.new_tag }}
          body: |
            ## Changelog
            $(git log ${{ steps.get_latest_tag.outputs.tag }}..HEAD --oneline)
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./
          asset_name: your_asset_name
          asset_content_type: application/zip
